platform :ios, '6.0'
xcodeproj 'Encore.xcodeproj'
pod 'AFNetworking',	'~> 1.3'
pod 'MBProgressHUD'
pod 'TestFlightSDK'
pod 'FlurrySDK'
pod 'XCDYouTubeVideoPlayerViewController'
pod 'SAMRateLimit'
pod 'Reachability'
pod 'LRGlowingButton'
#pod 'apptentive-ios'