platform :ios, '6.0'
xcodeproj 'Encore.xcodeproj'
pod 'AFNetworking',	'~> 1.3'
#pod 'Facebook-iOS-SDK', :inhibit_warnings => true
pod 'MBProgressHUD'
pod 'TestFlightSDK', '1.2.6'  
pod 'FlurrySDK', '4.2.2'
#pod 'JBKenBurnsView'
pod 'KNSemiModalViewController', '~> 0.3'
pod 'KNMultiItemSelector'