platform :ios, '6.0'
xcodeproj 'Encore.xcodeproj'
pod 'AFNetworking',	'~> 1.3'
pod 'Facebook-iOS-SDK'
pod 'MBProgressHUD'
#pod 'PSCollectionView'
#pod 'BDDynamicGridViewController'
#pod 'RFQuiltLayout'
#pod 'SGSStaggeredFlowLayout'
pod 'TestFlightSDK', '1.2'
pod 'FlurrySDK'
pod 'LBGIFImage'
pod 'FlatUIKit'